services:
  db-auth:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      - POSTGRES_USER=user_auth
      - POSTGRES_PASSWORD=pass_auth
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_auth -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: .
    container_name: auth-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user_auth:pass_auth@db-auth:5432/auth_db
      - APP_PUBLIC_URL=http://localhost:8081
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=0bazaarnoreply@gmail.com
      - SMTP_PASS=REDACTED_SMTP_APP_PASSWORD
      - SMTP_SSL=True
      - SMTP_STARTTLS=False
      - EMAIL_FROM=Bazaar Auth <0bazaarnoreply@gmail.com>
    depends_on:
      db-auth:
        condition: service_healthy